// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5uNdMPhG_-9NAcZRYtV33TKjPCLc1HzM',
    appId: '1:763254547597:web:d20d85562d375475972ec4',
    messagingSenderId: '763254547597',
    projectId: 'tamraj-kilvish',
    authDomain: 'tamraj-kilvish.firebaseapp.com',
    storageBucket: 'tamraj-kilvish.firebasestorage.app',
    measurementId: 'G-55KVDGGR03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUycGznKIvnp8OHdhq72wouhr9O0j6fwQ',
    appId: '1:763254547597:android:e33e1763d564f18a972ec4',
    messagingSenderId: '763254547597',
    projectId: 'tamraj-kilvish',
    storageBucket: 'tamraj-kilvish.firebasestorage.app',
  );
}
