// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBErCpJaK8YQUPwZR0WxApbDOA1Q05KTBw',
    appId: '1:14550226701:web:46cf230b8333bf89a58244',
    messagingSenderId: '14550226701',
    projectId: 'kilvish-aa125',
    authDomain: 'kilvish-aa125.firebaseapp.com',
    storageBucket: 'kilvish-aa125.appspot.com',
    measurementId: 'G-LN9PPCR88E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmc9XYW1fOMGyPa52R5y30xrUQG_-L4FI',
    appId: '1:14550226701:android:c9f384274cae633da58244',
    messagingSenderId: '14550226701',
    projectId: 'kilvish-aa125',
    storageBucket: 'kilvish-aa125.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDreiMeQh-Gh_nEXA6BGKsYwzE5YY16_S0',
    appId: '1:14550226701:ios:ed46398b7216de3aa58244',
    messagingSenderId: '14550226701',
    projectId: 'kilvish-aa125',
    storageBucket: 'kilvish-aa125.appspot.com',
    iosBundleId: 'com.example.kilvish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDreiMeQh-Gh_nEXA6BGKsYwzE5YY16_S0',
    appId: '1:14550226701:ios:ed46398b7216de3aa58244',
    messagingSenderId: '14550226701',
    projectId: 'kilvish-aa125',
    storageBucket: 'kilvish-aa125.appspot.com',
    iosBundleId: 'com.example.kilvish',
  );
}
